### PR TITLE
Filter by tags

### PR DESCRIPTION
**Pull request by Anne-Serine**
Made it possible to filter posts by tags, choosing the tag with a radio button and displaying the post(s) containing the selected tag.

### CODE REVIEW

**Review by StormSkoglund — APPROVED** [review]
Hi Anne-Serine, I was looking through your code and I couldn't see any errors. Your code also looks very different from mine, and you are much further ahead! But I tried to register and log in on the site you have deployed, but I didn't get to add my username in the login section. I wasn't therefore able to enter your site. Kind regards, Alex Storm Skoglund

**Comment by mar-ols** [comment]
Hello! I've gone through your site now and almost everything worked smoothly! :) Registering, login, creating, updating and deleting a post all works well. The only problem I had was with logging out. I was taken back to the login page momentarily, but then redirected back to the feed page every time. The profile and accesstoken also doesn't get deleted on logout, so I don't know if that has something to do with it. Great work overall! :)

**Comment by Anne-Serine** [comment]
> Hi Anne-Serine, I was looking through your code and I couldn't see any errors. Your code also looks very different from mine, and you are much further ahead! But I tried to register and log in on the site you have deployed, but I didn't get to add my username in the login section. I wasn't therefore able to enter your site. Kind regards, Alex Storm Skoglund

Thank you for having a look. That´s strange. Did you try more than once? It should work. May I ask why you wasn´t able to add your username. Didn´t the login page show up, or what seamed to be the problem?

**Comment by Anne-Serine** [comment]
> Hello! I've gone through your site now and almost everything worked smoothly! :) Registering, login, creating, updating and deleting a post all works well. The only problem I had was with logging out. I was taken back to the login page momentarily, but then redirected back to the feed page every time. The profile and accesstoken also doesn't get deleted on logout, so I don't know if that has something to do with it. Great work overall! :)

Thank you for testing and having a look. I have not made the Log out yet, so that´s why its not working as it should yet.

**Pull request merged**
